---
layout: post
tags: [react16 , errorBundary]
title: React16中的错误处理
date: 2018-05-21 10:01:22

---



## React15和更早版本中的行为
在过去，组件内部的JavaScript错误会破坏React的内部状态，并导致它在下一步的渲染中触发神秘错误 。该机制就导致了经常一个报错整个页面都挂掉了，停止渲染。很不友好。

## 错误边界
> 错误边界是在他们的子组件树中捕捉JavaScript错误，记录这些错误，并显示一个回退UI的React组件，而不是崩溃的组件树。

UI部分的一个JavaScript错误不应该破坏整个程序。为了给React用户解决这个问题，React16引入了“错误边界”的新概念。

## componentDidCatch
最主要是引入了一个新的生命周期 `componentDidCatch(error, info)`

如果一类组件定义了一个新的生命周期方法componentDidCatch(error, info)，那么这类组件就成为一个错误边界：

```javascript

class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  componentDidCatch(error, info) {
    // 显示回退UI
    this.setState({ hasError: true });
    // 你也可以把错误信息上报给错误上报服务器
    logErrorToMyService(error, info);
  }

  render() {
    if (this.state.hasError) {
      // 你可以渲染任何自定义的回退UI
      return <h1>Something went wrong.</h1>;
    }
    return this.props.children;
  }
}

```

然后就可以作为常规组件使用它：

```javascript
<ErrorBoundary>
  <MyWidget />
</ErrorBoundary>

```



## Live Demo
官方的例子 [A Pen by  Dan Abramov](https://codepen.io/gaearon/pen/wqvxGa?editors=0010)

## 在哪里放置错误边界
- App顶层放置
统一处理全局的错误提示
- 每个组件引用包裹起来
每个组件单独提示，只拦截一次
- @Decorator 装饰器处理组件
方便区别于生产环境和开发环境，灵活配置，可以和全局一起配置


## 另外的错误处理

-  try … catch
try / catch很伟大，但是它只适用于必要的代码：

```javascript
try {
  showButton();
} catch (error) {
  // ...
}
```


## 参考资料
- [Error Handling in React 16 - React Blog](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html)



